/**
 * Rewrite CORS-hostile pack URLs to CORS-friendly equivalents.
 *
 * `github.com/.../blob/...` and `.../raw/...` 302-redirect to
 * `raw.githubusercontent.com`, which DOES send
 * `Access-Control-Allow-Origin: *`. But browsers enforce CORS on the
 * initial hop (github.com, no CORS header) and block before they ever
 * see the redirect. Rewriting the URL client-side before the fetch
 * skips the bad hop entirely.
 *
 * Returns the URL unchanged when no rewrite applies — safe to call on
 * every pack-load.
 *
 * Future hosts to handle here: GitLab, Bitbucket, GitHub Gist.
 */
export function rewriteCorsHostileUrl(url: string): string {
  // github.com/USER/REPO/(blob|raw)/[refs/(heads|tags)/]REF/PATH
  //   → raw.githubusercontent.com/USER/REPO/REF/PATH
  // Covers: branches, tags, commit SHAs. Both `blob/` (web view) and
  // `raw/` (raw redirect) hit the same regex; raw.githubusercontent.com
  // accepts the same ref format.
  const gh = url.match(
    /^https?:\/\/github\.com\/([^/]+)\/([^/]+)\/(?:blob|raw)\/(?:refs\/(?:heads|tags)\/)?(.+)$/,
  );
  if (gh) {
    return `https://raw.githubusercontent.com/${gh[1]}/${gh[2]}/${gh[3]}`;
  }
  // gist.github.com/USER/HASH/raw/[REV/]FILE → gist.githubusercontent.com/...
  const gist = url.match(
    /^https?:\/\/gist\.github\.com\/([^/]+)\/([^/]+)\/raw\/(.+)$/,
  );
  if (gist) {
    return `https://gist.githubusercontent.com/${gist[1]}/${gist[2]}/raw/${gist[3]}`;
  }
  // github.com/USER/REPO/releases/download/TAG/ASSET — release assets
  // can't be rewritten because the final URL is a signed S3-style URL
  // generated by GitHub's CDN. The initial /releases/download/ hop
  // does NOT send CORS headers. Solution path requires the pack-proxy
  // (captured as a future task) — until then, releases need to be
  // re-hosted on raw.githubusercontent.com or another CORS-friendly
  // host. Returning the URL unchanged so the eventual fetch's CORS
  // error surfaces to the user with the real URL in the message.
  return url;
}
